name: Compress Images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Allow GitHub Actions to push changes

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default GitHub credentials

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pillow

      - name: Run Image Compression
        run: python .github/workflows/compress.py

            - name: Commit Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git add assets/images uploads/images
          git commit -m "Optimized images in assets/images and uploads/images" || exit 0
          git push origin main
